# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 569bdabb859a972af18f1c512e712fd1b6a01c48e77e4fb290d25f4c93d488656a03854b28f172e6b41a90cb98915a1dc63e646f7f7c31f80eb434cb9fac9bca

test:
  secret_key_base: 409b542e92c58478f05ae882915d3fb6c719f17af39792a78790dbb07df0fbd4b16c9f8f9f6cd953985ffbdec2d0c8128ee8dbc6b5fcbb2ef0841d9c9d98f9f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
